// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           23
// Async Callback (empty):               1
// Total number of exported functions:  26

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    stream_escrow
    (
        init => init
        upgrade => upgrade
        register => register
        topUpBond => top_up_bond
        setBillingGuards => set_billing_guards
        pause => pause
        resumeIfHealthy => resume_if_healthy
        cancelAndWithdraw => cancel_and_withdraw
        billEpoch => bill_epoch
        settleEpoch => settle_epoch
        enforceEpoch => enforce_epoch
        withdrawOwner => withdraw_owner
        setOperator => set_operator
        setWindowReward => set_window_reward
        setPromoSlots => set_promo_slots
        setMaxBackbillEpochs => set_max_backbill_epochs
        setHardMaxWindowsPerEpoch => set_hard_max_windows_per_epoch
        getAgentInfo => get_agent_info_view
        getAgentFinancials => get_agent_financials_view
        getEpochDebt => get_epoch_debt_view
        getEpochState => get_epoch_state_view
        getClaimableOwner => get_claimable_owner_view
        getConfig => get_config_view
        getPromoUsage => get_promo_usage_view
        getActiveAgentCount => get_active_agent_count_view
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
